### ISSUE TITLE
Staticman comments

### ISSUE THREAD

**Issue by luispuerto** [luispuerto/luispuerto.net#18]
I have to implement [Staticman comments](https://staticman.net). Perhaps I can wait until [gitlab implementation](https://github.com/eduardoboucas/staticman/issues/22) finish.  

This [tool](https://github.com/eduardoboucas/staticman/issues/145) could be interesting too. 

Some documentation: 

* https://snipcart.com/blog/staticman-dynamic-content-static-website
* https://mademistakes.com/articles/improving-jekyll-static-comments/
* https://mademistakes.com/articles/jekyll-static-comments/ 

Staticman now supports [threaded comments](url
https://github.com/eduardoboucas/staticman/issues/35) I have to check how mademistakes.com has done it.

**Comment by luisspuerto** [comment]
@VincentTam hey!! thanks a lot for the info. I have to get time to look at it and implement staticman on my site. It's already implemented but I think it's in a basic way... but I haven't look thoroughly to the MM outdates in my template.

**Comment by luisspuerto** [comment]
Hey! 

Thanks a lot for al the info @VincentTam I'll definitely take it a look in the near future.
